package driver

import (
	"database/sql"
	"time"

	_ "github.com/jackc/pgx/v5"
	_ "github.com/jackc/pgx/v5/stdlib"
)

const maxOpenConn = 15
const maxIdleConn = 15
const maxDBLifeTime = 5 * time.Minute

func ConnectSQL(dsn string) (*sql.DB, error) {
	d, err := NewDataBase(dsn)
	if err != nil {
		panic(err)
	}

	d.SetMaxOpenConns(maxOpenConn)
	d.SetMaxIdleConns(maxIdleConn)
	d.SetConnMaxLifetime(maxDBLifeTime)

	err = TestDB(d)
	if err != nil {
		return nil, err
	}

	err = CreateTabels(d)
	if err != nil {
		return nil, err
	}

	return d, nil
}

func CreateTabels(d *sql.DB) error {
	_, err := d.Exec(`
	CREATE TABLE IF NOT EXISTS public.countmetric (k integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,id varchar(100),val bigint,created timestamp default now());
	                                  
	CREATE TABLE IF NOT EXISTS public.gaugemetric (k integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,id varchar(100), val numeric(100,32), created timestamp default now());
	`)
	if err != nil {
		return err
	}

	return nil
}

func TestDB(d *sql.DB) error {
	err := d.Ping()
	if err != nil {
		return err
	}
	return nil
}

func NewDataBase(dsn string) (*sql.DB, error) {
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, err
	}

	if err = db.Ping(); err != nil {
		return nil, err
	}
	return db, nil
}
