// Code generated by go generate; DO NOT EDIT.
// This file was generated by genvar.go

package main

import (
	"fmt"
)

func printInfoVar() {
	print("Build vego vetrrsion", string(buildVersion))
	print("Build date", string(buildDate))
	print("Build commit", string(buildCommit))
}

func print(name string, val string) {
	if val == "" {
		fmt.Printf("%s: N/A\n", name)
	} else {
		fmt.Printf("%s: %s\n", name, val)
	}
}
